# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy only the source folder to avoid duplicating /src/src
COPY ./src ./src

# Publish the Calculation.Service project
RUN dotnet publish ./src/Calculation.Service/Calculation.Service.csproj -c Release -o /out

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .
EXPOSE 8080
ENTRYPOINT ["dotnet", "Calculation.Service.dll"]
